create schema VITRSA_SANDBOX;

CREATE SEQUENCE VITRSA_SANDBOX.VIT_RSA_GENERIC_SEQ
    START WITH 50002
INCREMENT BY 1;

CREATE TABLE VITRSA_SANDBOX.ACCOUNT_TYPE
(
   ACCOUNT_TYPE_ID BIGINT   NOT NULL ,
   MNEMONIC     VARCHAR(100) NOT NULL UNIQUE ,
   CREATION_DATE      DATE NOT NULL ,
   PRIMARY KEY (ACCOUNT_TYPE_ID)
);

CREATE TABLE VITRSA_SANDBOX.ACCOUNT_TYPE_TX
(
    TX_ID BIGINT        NOT NULL ,
    ACCOUNT_TYPE_ID BIGINT      NOT NULL ,
    MEBMBER_Id BIGINT       NOT NULL,
    TX_DATE     DATE   NOT NULL ,
    PRIMARY KEY (TX_ID),
    CONSTRAINT FK_ACCOUNT_TYPE_IDL FOREIGN KEY (ACCOUNT_TYPE_ID) REFERENCES VITRSA_SANDBOX.ACCOUNT_TYPE(ACCOUNT_TYPE_ID) ,

);
